# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: upKeeper.InstantPrivilegeAccess
PackageVersion: 1.7.0
PackageLocale: en-US
Publisher: upKeeper Solutions AB
PublisherUrl: https://upkeeper.se/en/
PrivacyUrl: https://upkeeper.se/en/privacy-policy/
PackageName: upKeeper Instant Privilege Access
PackageUrl: https://upkeeper.se/en/upkeeper-instant-privilege-access/
License: Proprietary
ShortDescription: upKeeper Instant Privilege Access is an organization-managed solution that gives Windows users temporary elevated privileges, configured via upKeeper Portal or local policy. It logs elevated actions and syncs records when back online.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
